sudo: required
services:
  - docker

before_install:
  - docker build -t blackstar500/multi-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true blackstar500/multi-react npm run test -- --coverage

after_success:
   - docker build -t blackstar500/multi-client ./client
   - docker build -t blackstar500/multi-nginx ./nginx
   - docker build -t blackstar500/multi-server ./server
   - docker build -t blackstar500/multi-worker ./worker
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   - docker push blackstar500/multi-client
   - docker push blackstar500/multi-nginx
   - docker push blackstar500/multi-server
   - docker push blackstar500/multi-worker

deploy:
   provider: elasticbeanstalk
   region: "eu-west-2"
   app: "multi-docker"
   env: "MultiDocker-env"
   bucket_name: "elasticbeanstalk-eu-west-2-914839102773"
   bucket_path: "docker-multi"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY


   #http://multidocker-env.eba-ttnakx4m.eu-west-2.elasticbeanstalk.com/
